name: clean_arch
description: Clean architecture generator for Flutter projects
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

executables:
  clean_arch:

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
